export const userEndpoints = {
  profile: "/user/profile",
  profileUpdate: "/user/profile/update",
  profileDelete: "/user/profile/delete",
  subscriptionCheck: "/user/subscription-check",
  subscriptionList: "/user/subscription/list",
  subscriptionStore: "/user/subscription/store",
  subscriptionCancel: "/user/subscription/cancel",
  stripeKeys: "/user/stripe-keys",
  stripeCheckoutSession: "/user/stripe/checkout-session",
  stripeCheckoutStatus: "/user/stripe/checkout-session/status",
  paymentList: "/user/payment/list",
  paymentStore: "/user/payment/store",
  addressList: "/user/address/list",
  addressStore: "/user/address/store",
  addressUpdate: (id: number) => `/user/address/update/${id}`,
  addressDelete: (id: number) => `/user/address/delete/${id}`,
  addressSetDefault: (id: number) => `/user/address/set-default/${id}`,
  walletSummary: "/user/wallet/summary",
  walletTransactionsList: "/user/wallet/transactions/list",
  contentStudyGuides: "/user/content/study-guides",
  contentNextPage: "/user/content/next-page",
  contentFlashCards: "/user/content/flash-cards",
  contentFlashCardSets: "/user/content/flash-cards/sets",
  contentFlashCardNextQuestion: "/user/content/flash-cards/next-question",
  questionSets: "/user/question/sets",
  questionSetQuestions: "/user/question/sets/questions",
  questionSubmitAnswer: "/user/question/submit-answer",
  cmsPageShow: "/cms-pages/show",
  adminAnalytics: "/admin/adminAnalytics",
} as const
